name: TelegramChat
main: de.Linus122.TelegramChat.TelegramChat
version: ${project.version}
authors: [Linus122]
softdepend: [Vault, SuperVanish, PremiumVanish, Chatty]
description: Brings minecraft chat to Telegram!
commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken
   linktelegram:
      description: Main command
      usage: /<command>
      permission: telegram.linktelegram
   tgon:
      description: Turn on telegram messages
      usage: /<command>
      permission: telegram.linktelegram
   tgoff:
      description: Turn off telegram messages
      usage: /<command>
      permission: telegram.linktelegram
   tgon:
      description: Turn on telegram messages
      usage: /<command>
      permission: telegram.linktelegram
   tgoff:
      description: Turn off telegram messages
      usage: /<command>
      permission: telegram.linktelegram
